version: '3.9'

services:
  rcon-uploader:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    env_file: devcontainer.env
    volumes:
      - ..:/workspace:cached
    # ports:
    #   - "8000:80"
    restart: "no"
    # network_mode: bridge

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"


  prometheus:
    image: prom/prometheus
    ports:
     - "9090:9090"
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
    # restart: unless-stopped
    restart: "no"
